### ISSUE TITLE
Multiple 32-bit games have stuttering issue

### ISSUE THREAD

**Issue by grapeharvest** [FNA-XNA/FAudio#205] opened 2020-08-13 19:31 UTC
@JohanSmet 
Duplicating report from [Wine Bugzilla](https://bugs.winehq.org/show_bug.cgi?id=48791)

```
diff --git a/src/FAudioFX_reverb.c b/src/FAudioFX_reverb.c
index bd58a06..b125b5f 100644
--- a/src/FAudioFX_reverb.c
+++ b/src/FAudioFX_reverb.c
@@ -101,7 +101,7 @@ static inline void DspDelay_Change(DspDelay *filter, float delay_ms)
 
 	/* Length */
 	filter->delay = MsToSamples(delay_ms, filter->sampleRate);
-	filter->read_idx = (filter->write_idx - filter->delay + filter->capacity) % filter->capacity;
+	filter->read_idx = (filter->write_idx + filter->delay + filter->capacity) % filter->capacity;
 }
 
 static inline float DspDelay_Read(DspDelay *filter)
```
Patch tested with Sniper Elite 3, Resident Evil 0 HD Remaster, Homesick.
Behaviour with non-affected games needs to be checked but it shouldn't be worse.

**Comment by JohanSmet** [comment] 2020-08-13 21:24
It's been a while but the original code seems okay to me. You want the read-pointer to be trailing behind the write-pointer so you read samples that were written delay_ms milliseconds ago. If you push the read-pointer before the write-pointer you'll try to read samples that haven't been written yet. Well, it's a ring-buffer so you'll read samples that were written in a earlier pass.

Maybe there is another issue with the stuttering games that gets masked by this change?

**Comment by grapeharvest** [comment] 2020-08-14 13:21
Obviously is something wrong.  Another question is why Homesick x64 works normally without any code change? Unlikely it's due to performance.

**Comment by flibitijibibo** [comment] 2020-08-14 13:49
Has this been tested on more than one PC and sound server configuration? For all we know this could just be happening on a 1st gen Athlon 64 using ALSA directly.

If something is definitely wrong this will be reproducible with the reverb test from the utils/ folder.

**Comment by grapeharvest** [comment] 2020-08-14 14:20
I don't think but probably somebody will also check this.  I'm on Intel Core 7th Gen and PulseAudio.

**Comment by grapeharvest** [comment] 2020-08-15 11:17
I get weird behaviour with the next settings in Reverb Test Tool:
1. Output Audio Engine - FAudio -> **Source Voice**
2. Wave file to play - Snare Drum (any) -> **Stereo**
3. Reverb effect -> **Enabled** - Preset (Underwater)

When I hit Play I hear some sound which stops immediately then I hit Stop and hear the tail. This is with enabled Stereo mode.
Behaviour is vice versa when Stereo mode is unchecked.

**Comment by JohanSmet** [comment] 2020-08-16 14:29
Ah yes, there's definitely something wrong when reverb is applied to a source voice.

FAudio stops processing a source voice when there's no more data to be decoded. The data that is appended by the reverb effect after the original sound is finished only plays when you hit stop and the source voice goes into PLAY_TAILS mode.

A quick hack to verify this with `testreverb` is to force the source voice into PLAY_TAILS mode when there are no more buffers queued up.
```
diff --git a/src/FAudio_internal.c b/src/FAudio_internal.c
index 3af8da9..dec2fa2 100644
--- a/src/FAudio_internal.c
+++ b/src/FAudio_internal.c
@@ -454,6 +454,8 @@ static void FAudio_INTERNAL_DecodeBuffers(
                                                        voice->src.format->nChannels
                                                )
                                        );
+
+                                       voice->src.active = 2;
                                }
```
But that's obviously not something you'd want to commit ;-) 

I guess the solution is to change `FAudio_INTERNAL_MixSource` to keep running the effect chain until the `OutputProcessParameters` of the effect chain have the `FAPO_BUFFER_SILENT` flag?

**Comment by flibitijibibo** [comment] 2020-08-16 14:32
That makes sense to me, just need to figure out how to make it so the effect chain is still processed when no buffers are active without making every source run PLAY_TAILS by accident.

**Comment by flibitijibibo** [comment] 2020-08-17 14:36
Latest FAudio commit fixes the testreverb repro case, but I'm still curious to know if this fixes the games mentioned in the WineHQ report.

**Comment by grapeharvest** [comment] 2020-08-17 18:50
Yes, testreverb is good now, but games are still stutter.

**Comment by flibitijibibo** [comment] 2020-08-19 19:56
I believe I asked this last time, but do any of these games work with `SDL_AUDIODRIVER=disk`? If you can get .raw file from at least one of those games I can analyze it and see what we're looking at.

**Comment by grapeharvest** [comment] 2020-09-08 14:52
Fine, can we use `static inline` **uint32_t** `DspDelay_Process(DspDelay *filter, float sample_in)` ?

**Comment by flibitijibibo** [comment] 2020-09-08 14:53
Does that actually improve performance?

**Comment by grapeharvest** [comment] 2020-09-08 14:57
Yes, no more stuttering.

**Comment by flibitijibibo** [comment] 2020-09-08 14:57
Cool, post the git diff and I'll get it into master today.

**Comment by flibitijibibo** [comment] 2020-09-08 15:02
Hang on, this is changing the return type and not just inlining something? How does that even work? If you're passing u32 instead of float you're shredding the sample data, there's no way that sounds good. If that's fixing _anything_ it's working around your FPU being so slow that changing a single return type fixed performance.

**Comment by grapeharvest** [comment] 2020-09-08 16:25
The next shot in the darkness - I still get an output while this line is commented out `DspDelay_Write(filter, sample_in);` with no sound issues.

**Comment by flibitijibibo** [comment] 2020-09-08 18:03
If it doesn't store delay you lose reverb. You cannot just arbitrarily change and remove code and expect it to work, stop doing that. Optimization is taking existing code and making it do the same thing but faster, which is entirely different.

**Comment by grapeharvest** [comment] 2020-09-08 19:11
I'm just trying to understand what parts of code somehow related to the issue.  Have any better ideas - I'll try with the great pleasure. Using -O3 flag gives the same result as without it.  And btw, Beyond: Two Souls which is 64-bit only is also issued.

**Comment by flibitijibibo** [comment] 2020-11-01 16:08
Closing this as it turned out to be external. The problem was one system's performance, rather than any particular issue in FAudioFX.

**Closed by flibitijibibo** 2020-11-01 16:08 UTC
