### ISSUE TITLE
Final Fantasy XIV 5.0 crash in FAudioFXVolumeMeter_Process

### ISSUE THREAD

**Issue by achurch** [FNA-XNA/FAudio#152] opened 2019-06-28 19:14 UTC
As mentioned at https://github.com/ValveSoftware/Proton/issues/580#issuecomment-506812844, the latest update to FFXIV crashes on game start in `FAudioFXVolumeMeter_Process`. https://github.com/FNA-XNA/FAudio/commit/6de5c86b27ec3c5f3aac2dab431563a89a1460b2 doesn't seem to have helped; the crash is still in the dereference of `levels->pPeakLevels`, which appears to have been clobbered. I'm still trying to find the clobberer, but the clobbering value appears to be consistently 0x1e42c80000 (0x42c80000 == 100.0f).

Will add more information as I analyze the problem.

**Comment by flibitijibibo** [comment] 2019-06-28 19:42
Change this to return if m_fProducer is true:

https://github.com/FNA-XNA/FAudio/blob/master/src/FAPOBase.c#L395

**Comment by achurch** [comment] 2019-06-28 19:47
That fixes the crash and allows the game to start, but there's no sound.

**Comment by achurch** [comment] 2019-06-28 20:11
Following up, gameplay in general seems to be unaffected; the lack of sound is the only apparent issue.

Without a crash to follow, I don't know enough about the XAudio API to easily investigate this further. Let me know if there's anything else you'd like me to try.

**Comment by flibitijibibo** [comment] 2019-06-28 20:23
Tried this with upstream FAudio on Windows and the issue does not occur for me. More importantly, I also don't see any instance of them calling SetParameters on the VolumeMeter object. This suggests there's something external going on that's separate from what FAudio is actually doing.

(For reference, in addition to it working on my machine, the same code is also shipping in FFXIV Mac, so I'm curious as to why the original assertion was even getting hit...)

**Comment by achurch** [comment] 2019-06-28 20:29
Is it possible Wine's FAudio-based xaudio2_*.dll is doing something wrong to cause a SetParameters call on the wrong instance, thus ending up with two calls on the same instance and none on a separate instance? Pointers getting mixed up somewhere or the like?

A quick scan of the Wine sources (I'm using 4.11) suggests they're just a thin wrapper around FAudio so it doesn't seem likely, unless the vtbl definition is somehow wrong and some completely different call is getting forward to SetParameters.

**Comment by flibitijibibo** [comment] 2019-06-28 20:32
The xaudio_dll sources won't be the issue. Both the old COM wrapper and Wine sources will effectively be the same for this game. At best I can only assume the effect chain is out of order, so SetParameters is being called on the wrong index and causing the assertion failure. This is probably what you care about:

https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio.c#L1317
https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio.c#L1414

**Comment by flibitijibibo** [comment] 2019-06-28 20:44
Just tried with Proton 4.11-GE and couldn't reproduce the issue. Exact process I went through:

1. Download/update/launch FFXIV from Windows (because ugh 30437)
2. Copy install to `steamapps/common/`
3.
```
mkdir ~/.steam/root/compatibilitytools.d/
cd ~/.steam/root/compatibilitytools.d
curl -O https://github.com/GloriousEggroll/proton-ge-custom/releases/download/4.11-GE-1/Proton-4.11-GE-1.tar.gz
tar xvfz Proton-4.11-GE-1.tar.gz
git clone git://github.com/FNA-XNA/FAudio.git
mkdir FAudio/flibitBuild
cd FAudio/flibitBuild
cmake ..
make -j8
cp cp libFAudio.so.0.19.06 ~/.local/share/Steam/compatibilitytools.d/Proton-4.11-GE-1/dist/lib64/libFAudio.so.0.19.06
```
4. Run game, audio seems fine?

**Comment by achurch** [comment] 2019-06-28 20:59
Unfortunately I don't have space on my laptop for a second FFXIV install (away from home at the moment) but I'll try swapping libraries around between vanilla Wine and that Proton package and see if I can pinpoint the cause.

**Comment by flibitijibibo** [comment] 2019-06-28 21:04
Alrighty, for now it looks like FAudio, the COM wrapper, and the Wine DLL (Proton and upstream are the same) appear to be safe, so we're looking at a variance outside of all three upstream projects. Closing the issue here since this is almost certainly something introduced just for https://github.com/ValveSoftware/Proton/issues/580, I'll be subscribed to that thread.

**Closed by flibitijibibo** 2019-06-28 21:04 UTC
