### ISSUE TITLE
Audio panning and weirdness(3D Audio Issue?) Skyrim SE Proton

### ISSUE THREAD

**Issue by DGxInfinitY** [FNA-XNA/FAudio#110] opened 2019-02-17 04:52 UTC
In Skyrim SE (Special Edition) I have to use FAudio to get any voice to work properly. This, of course, was quite easy and not hard at all. The only issue is that Voice gets a little messed up. When facing the character dialog is easily heard however when looking away even if the character is close audio drops out. I believe this to be a problem caused by the lack of full 3d audio support/implementation. If you could confirm that that would be awesome. I also notice in some dialog during the sentence the character repeats a word and the sentence gets cut off and the end. This isn't a huge deal and perhaps isn't an FAudio issue rather a Windows issue. I also get weird Reverb in certain buildings within the game. Again not game breaking but something to note.

**Comment by flibitijibibo** [comment] 2019-02-17 04:57
Duplicate of https://github.com/ValveSoftware/Proton/issues/4, but here are some good places to explore:

https://github.com/FNA-XNA/FAudio/blob/master/src/F3DAudio.c#L1422

https://github.com/FNA-XNA/FAudio/blob/master/src/FAudioFX_reverb.c#L1397

**Closed by flibitijibibo** 2019-02-17 04:57 UTC
