### ISSUE TITLE
Major sound issues in XCOM 2 War of Chosen

### ISSUE THREAD

**Issue by Alexander--** [FNA-XNA/FAudio#188] opened 2020-05-09 11:26 UTC
wine version: Staging 5.7
faudio version: 20.04

Running Windows version of XCOM 2 War of Chosen from GOG.

The voiceover is lagging behind action in dialogues, there is constant echo and sound dips (also described as "trembling sound" in forums), overall the sound is unusable.

Changing XAudio2_7 to "native" in winecfg fixes all those issues.

**Comment by flibitijibibo** [comment] 2020-05-09 13:52
In addition to full WINEDEBUG=+xaudio2 logs I will need a standalone program to reproduce this or a gifted copy of the game (at which point, just get [the real thing](https://www.feralinteractive.com/en/games/xcom2/xcom2warofthechosen/)), for all I know it could be that Pulse needs to be restarted.

**Comment by flibitijibibo** [comment] 2020-05-29 18:26
Closing due to old age, as no information was provided - this can be reopened when tested with 20.06 (scheduled for Monday) and logged as described above.

**Closed by flibitijibibo** 2020-05-29 18:26 UTC

**Comment by Alexander--** [comment] 2020-06-21 04:59
Ori and the Will of the Wisps also suffers from the similar (same?) issue. Heavy staggering/echoes can be heard immediately after entering main menu. Installing xact and force-enabling Microsoft xaudio2 dlls in winecfg also fixes the issue in this case.

Tested with faudio 20.06.

I forgot to mention an important detail: I am using Wine with bare ALSA (no pulseaudio, only Dmix). I know, that this setup is increasingly unpopular, but hopefully it is still supported.

**Comment by Alexander--** [comment] 2020-06-21 05:14
[wine log, taken with WINEDEBUG=+xaudio](https://gist.githubusercontent.com/Alexander--/9a7dd0fe0b96cfc86df285019930899c/raw/cd7d820a88d90fabe5bd5da2572dd1f9a0b2a4ee/xaudio.log)

[asound.conf](https://gist.githubusercontent.com/Alexander--/fd34ee9b61b5756d8852cff3bb96f18c/raw/8f8ab6199aa7740a0e7c69234d5d0a70d01001d2/asound.conf)
