### ISSUE TITLE
avcodec_register_all() missing?

### ISSUE THREAD

**Issue by knecht** [FNA-XNA/FAudio#114] opened 2019-02-25 23:45 UTC
avcodec_find_decoder(AV_CODEC_ID_WMAV2) always returns NULL unless I call avcodec_register_all() first.

After I inserted a call to avcodec_register_all in FAudio_FFMPEG_init I heard npc voices in Skyrim SE. 
Not sure whether FAudio_FFMPEG_init is the right place for this, though.

**Comment by flibitijibibo** [comment] 2019-02-26 16:02
Duplicate of #107 - we were looking for a better call than `avcodec_register_all` but it never materialized. At the moment we require FFmpeg 4+, but if someone can make it so only WMA is registered rather than everything supported in the FFmpeg build (!), we can bump the requirement down to version 3+.

**Closed by flibitijibibo** 2019-02-26 16:02 UTC
