### ISSUE TITLE
Far Cry 4

### ISSUE THREAD

**Issue by SR-dude** [FNA-XNA/FAudio#116] opened 2019-03-02 02:16 UTC
For Far Cry 4, I get audio during the videos only. This is with a development 4.3
release, with FAudio added as system libraries. Wine compiles with xaudio2 support.
I compile wine with Pulseaudio  support. 

Trying to find out where the stream is going, I watched the game with the pulse
volume control. It is as below. <-vol+> when the videos are playing is clearly
normal. <-vol+> jumps up and down as you would expect for any stream. Then, when the
videos are finished and you are at the main menu in the game, audio stream #2 
disappears. <-vol+> for the wine preloader app  is dead. No audio is being sent
to pulse by SDL2. 
`FarCry4.exe: audio stream #2 on                [HD-Audio Generic Analog Stereo]`
`<-vol+>  <- this jumps up/down`
`wine64-preloader: Simple DirectMedia Layer on  [HD-Audio Generic Analog Stereo]`
`<nothing>`

To get audio working for this game, I would have to override xaudio 2.7.
Should I just wait this one out? Or is there some way to find out what 
exactly SDL2 is sending pulse? 

When I compile SDL2 I don't use any special configuration options. But, I did look
up debian.

> --enable-sdl-dlopen --disable-nas --disable-esd --disable-arts --disable-alsa-shared --disable-pulseaudio-shared

**Comment by flibitijibibo** [comment] 2019-03-02 02:26
Even though this is with upstream Wine I’ll mark this as a duplicate of https://github.com/ValveSoftware/Proton/issues/2143 since it’s essentially the same xaudio2 implementation. There’s also the WineHQ Bugzilla: https://bugs.winehq.org/show_bug.cgi?id=43173

My first guess is that it’s WMA, but a proper log would be needed (something like PROTON_LOG=1) to know for sure.

**Closed by flibitijibibo** 2019-03-02 02:26 UTC

**Comment by SR-dude** [comment] 2019-03-02 03:07
I'm not a proton user.  I use wine development releases.  So, I'm not sure I can contribute there, with the tone of the report being issues concerning uplay. The mod there did tag it with 'xaudio2',

**Comment by flibitijibibo** [comment] 2019-03-02 03:20
The Bugzilla will be the best place then - this should be helpful as well:

https://wiki.winehq.org/FAQ#How_can_I_get_a_debugging_log_.28a.k.a._terminal_output.29.3F
