### ISSUE TITLE
No SFX in TrackMania Nations Forever in Proton 4.11

### ISSUE THREAD

**Issue by qwertychouskie** [FNA-XNA/FAudio#155] opened 2019-08-02 20:19 UTC
When running TrackMania Nations Forever in Proton 4.11 (which should include the latest FAudio), all the in-game sound effects don't play.  More specifically, anything that is an ogg in the data files seems to work fine (music, ambient wind, even turbines when driving by), but everything else (WAV) doesn't work.  I compiled FAudio with building of utils enabled and played a WAV with `./testxwma '/home/qwerty/.local/share/wineprefixes/steam/drive_c/Program Files/Steam/steamapps/common/TrackMania Nations Forever/GameData/Interface/Media/Audio/Sound/Wav/RaceGo.wav'`, a sound I know is not playing in-game, and it worked just fine.  I'm happy to help wherever I can.

Info about one of the WAVs (as per VLC's media info):
```
Stream 0
  Codec: PCM S16 LE (s16l)
  Type: Audio
  Channels: Stereo
  Sample rate: 44100 Hz
  Bits per sample: 16
```

**Comment by flibitijibibo** [comment] 2019-08-02 22:04
Duplicate of https://github.com/ValveSoftware/Proton/issues/467

If I’m not mistaken this is a 32-bit game, and Proton defaults to the DXSDK version of XAudio2. The PROTON_LOG=1 output will likely confirm this.

**Closed by flibitijibibo** 2019-08-02 22:04 UTC

**Comment by qwertychouskie** [comment] 2020-04-29 04:00
For future reference, this was a bug in Wine's dsound code, and was recently fixed upstream.  More details in https://github.com/ValveSoftware/Proton/issues/467.
