### ISSUE TITLE
Fallout 4 FAudio [wmav2 @ 0x7f9ad0135d80] prev_block_len_bits 4 out of range

### ISSUE THREAD

**Issue by t14462** [FNA-XNA/FAudio#133] opened 2019-04-30 21:09 UTC
Fallout 4 freezing (or sound disappearing) with spam of tons console messages:

[wmav2 @ 0x7f9ad0135d80] prev_block_len_bits 4 out of range

INFO System-wide FAudio, not winetricks one

Repo and AUR-git version doing same problem

**Comment by flibitijibibo** [comment] 2019-04-30 22:36
Duplicate of https://github.com/ValveSoftware/Proton/issues/308

**Closed by flibitijibibo** 2019-04-30 22:36 UTC
