### ISSUE TITLE
The Child of Light: sound works only during cutscenes

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [FNA-XNA/FAudio#137] opened 2019-05-29 23:44 UTC
The Child of Light has some issues with Faudio wine wrappers. I use Faudio 19.05, and the sound works only during cutscenes, but inside the game there is no sound in the menus or during gameplay.

**Comment by flibitijibibo** [comment] 2019-05-29 23:48
Duplicate of https://github.com/ValveSoftware/Proton/issues/2463 (Even if this is vanilla Wine it's still the same issue)

**Closed by flibitijibibo** 2019-05-29 23:48 UTC

**Comment by ahmed-elsayed2017** [comment] 2019-05-30 00:21
No, the sound works without any problems with Wine-staging without Faudio wine wrappers.

**Comment by ahmed-elsayed2017** [comment] 2019-05-31 16:32
A Story About My Uncle has the same issue. Both are 32bit, and DX9 games.
