### ISSUE TITLE
Dragon Quest Heroes Crash

### ISSUE THREAD

**Issue by mrdeathjr28** [FNA-XNA/FAudio#103] opened 2019-01-02 15:35 UTC
Hi

Dragon quest heroes crash when enter in game and similar situation occurs in berserk and the hawk band

This is backtrace of crash in both games

[dqhbacktrace.txt](https://github.com/FNA-XNA/FAudio/files/2721152/dqhbacktrace.txt)

[berserkbacktrace.txt](https://github.com/FNA-XNA/FAudio/files/2721153/berserkbacktrace.txt)

Thanks

**Comment by flibitijibibo** [comment] 2019-01-02 15:39
Duplicate of https://github.com/ValveSoftware/Proton/issues/779

**Closed by flibitijibibo** 2019-01-02 15:39 UTC
