### ISSUE TITLE
No sound in Skyrim LE

### ISSUE THREAD

**Issue by Kron4ek** [FNA-XNA/FAudio#101] opened 2018-12-18 19:16 UTC
When i run Skyrim Legendary Edition with FAudio dlls, i get such error:

`00eb:err:ole:COMPOBJ_DllList_Add couldn't find function DllGetClassObject in L"C:\\windows\\system32\\xaudio2_6.dll"`

And therefore, there is no sound in game.

Used commit: 13ef41ce8cf52ccaa3dbc8044886e0e9d810bc04

**Comment by flibitijibibo** [comment] 2018-12-18 19:17
Duplicate of https://github.com/ValveSoftware/Proton/issues/4

**Closed by flibitijibibo** 2018-12-18 19:17 UTC

**Comment by Kron4ek** [comment] 2018-12-18 19:33
@flibitijibibo Yep, sound works with DX redist, but i thought it will work with FAudio too. I also forgot to say, that i use MinGW build, if that matters.

**Comment by flibitijibibo** [comment] 2018-12-18 19:36
Of the three options (DX, builtin, MinGW), MinGW is probably the least functional since it gets the least attention (and at some point it will probably be discontinued). builtin will work if you configure the prefix to use builtin first, otherwise the default is to fall back to native (in Proton at least, I don't think this will be the case for vanilla Wine).
