### ISSUE TITLE
terrible noises on Owlboy ARM

### ISSUE THREAD

**Issue by Askmewho** [FNA-XNA/FAudio#230] opened 2020-11-17 13:15 UTC
Hi, I tested this game with mono on RPI3 and didnt have this issues at all, now its a disaster, the music sounds perfect, but the sound effects are extremely loud and distorted. How could I debug it to report more detailed information about it? thanks

**Comment by flibitijibibo** [comment] 2020-11-17 13:19
Owlboy is known to work with upstream on x86_64 - our NEON paths are also known to be stable. You can try to set SDL_AUDIODRIVER=disk and try to make sense of the raw output, but this is probably not FAudio's issue.

**Comment by Askmewho** [comment] 2020-11-17 14:11
oka, yeah, so maybe it's a pulse thing I guess. I tried with alsa but it's the same. not exacly sure how to read that .raw output 

[sdlaudio.raw.zip](https://github.com/FNA-XNA/FAudio/files/5553936/sdlaudio.raw.zip)

**Comment by Askmewho** [comment] 2020-11-18 00:41
thanks anyway for the help. if you can't give me a hint (bc it's not your work) , close it.

**Comment by flibitijibibo** [comment] 2020-11-18 15:33
Closing since Pi is sort of outside our support reach. If this can be reproduced on x86_64 this can be reopened.

**Closed by flibitijibibo** 2020-11-18 15:33 UTC
